---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base
inputs:
  - name: tools
  - name: repo
  - name: keyval
outputs:
  - name: out
  - name: keyvalout
  - name: sonarqube-analysis-input
caches:
  - path: gradle
  - path: maven
run:
  path: tools/concourse/tasks/build-and-upload/task.sh
